services:

  redis:
    container_name: redis
    image: redis:alpine
    # ports:
      # - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5


  postgres:
    container_name: postgres
    image: postgres:latest
    env_file:
      - .env
    # ports:
      # - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d ws_chat_db" ]
      interval: 5s
      timeout: 5s
      retries: 5


  celery:
    container_name: celery
    build:
      context: ./celery
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy

  
  bot:
    container_name: bot
    build:
      context: ./bot
    env_file:
      - .env


  fastapi:
    container_name: fastapi
    build:
      context: ./fastapi
    env_file:
      - .env
    # ports:
     # - "8000:8000"
    command: >
      sh -c "alembic upgrade head && uvicorn run:app --host 0.0.0.0 --port 8000"
    # command: uvicorn run:app --host 0.0.0.0 --port 8000
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      celery:
        condition: service_started

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      # - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.cong:/etc/nginx/cong.d/nginx.conf
      - ./fastapi/static/:/static
    depends_on:
      fastapi:
        condition: service_started

